version: '3.8'

services:
  cors-proxy:
    image: redocly/cors-anywhere
    container_name: jira-timesheet-cors-proxy
    ports:
      - "8081:8080"
    environment:
      - CORSANYWHERE_WHITELIST=
    restart: unless-stopped
    networks:
      - jira-timesheet

networks:
  jira-timesheet:
    driver: bridge
